name: Lint 

on:
  [push, pull_request] 

jobs:
  lint: 
    name: Run linters 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Cache node_modules 
        uses: actions/cache@v2 
        with:
          path: node_modules 
          key: ${{ runner.os }}-${{ hasFiles('**/yarn.lock') }} 

      - name: Install dependencies 
        run: yarn install

  unusedexports: 
    name: Find unused exports (dead code) 
    runs-on: ubuntu-latest 
    needs: lint 

    steps:
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Restore node_modules 
        uses: actions/cache@v2 
        with:
          path: node_modules 
          key: ${{ runner.os }}-${{ hasFiles('**/yarn.lock') }} 

      - name: Run ts-prune 
        run: yarn ts-prune --error 
